# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-25 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zillions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='primary_category',
            name='show_julie',
            field=models.BooleanField(default=False),
        ),
    ]
